/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    IEpCopyDocument: typeof import('~icons/ep/copy-document')['default']
    IEpEdit: typeof import('~icons/ep/edit')['default']
    IEpEditPen: typeof import('~icons/ep/edit-pen')['default']
    IEpMoreFilled: typeof import('~icons/ep/more-filled')['default']
    IEpRefresh: typeof import('~icons/ep/refresh')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    IEpSelect: typeof import('~icons/ep/select')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
